#
# Config

config:

  # Limit of jobs each player.
  limit-jobs: 3

  formula:

    # Formula for gain money per level:
    gain-money: "%money * %level%"

    # Formula for gain xp per level:
    gain-xp: "%xp * %level%"

    # Formula for max xp:
    max-xp: "%level% * 5"

  action-bar:

    # Format to gain rewards:
    gain-rewards: "&a%money%$+ &8- &a%xp%+"
#
# List of jobs.
jobs:

  # Miner
  miner:

    # Name of the job:
    name: "Miner"

    # Type [PLAYER_BREAK_BLOCK, PLAYER_PLACE_BLOCK, PLAYER_KILL_ENTITY]
    type: PLAYER_BREAK_BLOCK

    # List of items
    # Format: ITEM, GAIN_MONEY, GAIN_XP_JOB: Example: COBBLESTONE, 5, 5
    items:
      - "COBBLESTONE, 5, 2"