#
# Config

config:

  # Limit of jobs each player.
  limit-jobs:

    groups:

      # Default limit.
      default: 3

      # Group multiplier [Need a plugin permision]:
      vip: 5

    # Permission to bypass
    bypass-permission: vip.bypass

  # Disable creative mode:
  disable-creative: true

  # Disable silk touch:
  disable-silk-touch: true

  # Set max level to get.
  max-level-jobs: 200

  multiplier:

    # To broadcast the multiplier. Put 'none' to disable this option.
    broadcast: none

    # Default multiplier
    default: 1.0

    # Group multiplier [Need a plugin permision]:
    group:
  #     vip: 2.0
  #     vip+: 3.0

  formula:

    # Formula for gain money per level:
    gain-money: "%money% * %level%"

    # Formula for gain xp per level:
    gain-xp: "%xp% * %level%"

    # Formula for max xp:
    max-xp: "(%level% * %level%) * 10"

  action-bar:

    # Format to gain rewards:
    gain-rewards: "&a+%money%$ &8- &f+%xp%XP"

  # Reward when you increase a level:
  rewards:

    config:

      # To enable the option.
      enabled: false

    # This path is a the level when you increase:
    10:
      # All formats: [ADD-MONEY] [BROADCAST] [COMMAND]
      format:
        - "[ADD-MONEY] 500"
        - "[BROADCAST] &aThe player &a%player% won the level 10"
        - "[COMMAND] give %player% diamond "



#
# List of jobs.
jobs:

  # Miner job:
  miner:

    # Name of the job:
    name: "Miner"

    # Type [PLAYER_BREAK_BLOCK, PLAYER_PLACE_BLOCK, PLAYER_KILL_ENTITY]
    type: PLAYER_BREAK_BLOCK

    # Allow global stats
    global_stats: true

    # List of items
    items:

      # Format: money: GAIN_MONEY, xp: GAIN_XP_JOB:

      STONE:

        money: 1
        xp: 1

        enabled_stats: false

      COAL_ORE:
        money: 2
        xp: 2

        enabled_stats: false

      IRON_ORE:
        money: 2
        xp: 2

        enabled_stats: false

      GOLD_ORE:
        money: 3
        xp: 3

        enabled_stats: false

      DIAMOND_ORE:
        money: 5
        xp: 5

        enabled_stats: false

      EMERALD_ORE:
        money: 4
        xp: 4

        enabled_stats: false

      REDSTONE_ORE:
        money: 3
        xp: 4

        enabled_stats: false

      LAPIZ_ORE:
        money: 3
        xp: 3

        enabled_stats: false

  # Woodcutter jobb
  woodcutter:
    name: "Woodcutter"

    # Type [PLAYER_BREAK_BLOCK, PLAYER_PLACE_BLOCK, PLAYER_KILL_ENTITY]
    type: PLAYER_BREAK_BLOCK

    # Load global stats
    global_stats: false

    # List of items
    items:
      ACACIA_LOG:

        money: 1
        xp: 1

        enabled_stats: false

      BIRCH_LOG:

        money: 1
        xp: 1

        enabled_stats: false

      DARK_OAK_LOG:

        money: 1
        xp: 1

        enabled_stats: false

      JUNGLE_LOG:

        money: 1
        xp: 1

        enabled_stats: false

      MANGROVE_LOG:

        money: 1
        xp: 1

        enabled_stats: false

      OAK_LOG:

        money: 1
        xp: 1

        enabled_stats: false

  # Builder job
  builder:
    # Name of the job:
    name: "Builder"

    # Type [PLAYER_BREAK_BLOCK, PLAYER_PLACE_BLOCK, PLAYER_KILL_ENTITY]
    type: PLAYER_PLACE_BLOCK

    # Load global stats
    global_stats: false

    # List of items
    items:
      # Format: money: GAIN_MONEY, xp: GAIN_XP_JOB:
      # Enable stats: For enable data in /jobs info miner.

      STONE:

        money: 1
        xp: 1

        enabled_stats: false

      ACACIA_WOOD:

        money: 1
        xp: 1

        enabled_stats: false

      BIRCH_WOOD:

        money: 1
        xp: 1

        enabled_stats: false

      DARK_OAK_WOOD:

        money: 1
        xp: 1

        enabled_stats: false

      JUNGLE_WOOD:

        money: 1
        xp: 1

        enabled_stats: false

      MANGROVE_WOOD:

        money: 1
        xp: 1

        enabled_stats: false

      OAK_WOOD:

        money: 1
        xp: 1

        enabled_stats: false

      ACACIA_PLANKS:

        money: 1
        xp: 1

        enabled_stats: false

      BIRCH_PLANKS:

        money: 1
        xp: 1

        enabled_stats: false

      DARK_OAK_PLANKS:

        money: 1
        xp: 1

        enabled_stats: false

      JUNGLE_PLANKS:

        money: 1
        xp: 1

        enabled_stats: false

      MANGROVE_PLANKS:

        money: 1
        xp: 1

        enabled_stats: false

      OAK_PLANKS:

        money: 1
        xp: 1

        enabled_stats: false

      QUARTZ:

        money: 2
        xp: 2

        enabled_stats: false

      DIAMOND_BLOCK:
        money: 10
        xp: 10

        enabled_stats: false

      EMERALD_BLOCK:
        money: 8
        xp: 8

        enabled_stats: false

      IRON_BLOCK:
        money: 5
        xp: 5

        enabled_stats: false

      REDSTONE_BLOCK:
        money: 5
        xp: 5

        enabled_stats: false

      GOLD_BLOCK:
        money: 5
        xp: 5

        enabled_stats: false

      CARBON_BLOCK:
        money: 2
        xp: 2

        enabled_stats: false

  # Hunter job
  hunter:
    # Name of the job:
    name: "Hunter"

    # Type [PLAYER_BREAK_BLOCK, PLAYER_PLACE_BLOCK, PLAYER_KILL_ENTITY]
    type: PLAYER_KILL_ENTITY

    # Load global stats
    global_stats: false

    # List of items
    items:
      # Format: money: GAIN_MONEY, xp: GAIN_XP_JOB:

      PLAYER:
        money: 10
        xp: 10

        enabled_stats: false

      PIG:
        money: 5
        xp: 5

        enabled_stats: false

      COW:
        money: 5
        xp: 5

        enabled_stats: false

      MUSHROM_COW:
        money: 5
        xp: 5

        enabled_stats: false

      ZOMBIE:
        money: 5
        xp: 5

        enabled_stats: false

      SKELETON:
        money: 5
        xp: 5

        enabled_stats: false

      SPIDER:
        money: 5
        xp: 5

        enabled_stats: false

      CREEPER:
        money: 5
        xp: 5

        enabled_stats: false

