#
# Config

config:

  # Limit of jobs each player.
  limit-jobs: 3

  formula:

    # Formula for gain money per level:
    gain-money: "%money% * %level%"

    # Formula for gain xp per level:
    gain-xp: "%xp% * %level%"

    # Formula for max xp:
    max-xp: "(%level% * %level%) * 10"

  action-bar:

    # Format to gain rewards:
    gain-rewards: "&a+%money%$ &8- &f+%xp%XP"
#
# List of jobs.
jobs:

  # Miner
  miner:

    # Name of the job:
    name: "Miner"

    # Type [PLAYER_BREAK_BLOCK, PLAYER_PLACE_BLOCK, PLAYER_KILL_ENTITY]
    type: PLAYER_BREAK_BLOCK

    # List of items
    items:

      # Format: money: GAIN_MONEY, xp: GAIN_XP_JOB:

      STONE:

        money: 1
        xp: 1

      COAL_ORE:
        money: 2
        xp: 2


      IRON_ORE:
        money: 2
        xp: 2

      GOLD_ORE:
        money: 3
        xp: 3

      DIAMOND_ORE:
        money: 5
        xp: 5

      EMERALD_ORE:
        money: 4
        xp: 4

      REDSTONE_ORE:
        money: 3
        xp: 4

      LAPIZ_ORE:
        money: 3
        xp: 3

