main: me.bryang.workity.Workity

name: Workity
version: ${project.version}

api-version: 1.13

author: BryanG
description: A job plugin.

softdepend:
  - Vault

commands:

  jobs:

    description: Main command.
    aliases:
      - workity
      - work

    usage: /jobs help.

