main: me.bryang.labority.Labority
name: Labority
version: ${project.version}

api-version: 1.13

softdepend:
  - Vault

commands:
  jobs:
    description: Main command.
    aliases:
      - labority
      - labor

    usage: /jobs help.